package com.ui.audi.tokens

import com.ui.core.engine.api.ThemeTokenAccessor

// Generated by scripts/generate_tokens.py — do not edit by hand.
@Suppress("MatchingDeclarationName", "ClassName", "ObjectPropertyNaming")
object Sem {
    object Blur {
        val Card = ThemeTokenAccessor("Sem.Blur.Card")
        val Cover = ThemeTokenAccessor("Sem.Blur.Cover")
        val Interactive = ThemeTokenAccessor("Sem.Blur.Interactive")
        val LG = ThemeTokenAccessor("Sem.Blur.LG")
        val MD = ThemeTokenAccessor("Sem.Blur.MD")
        val SM = ThemeTokenAccessor("Sem.Blur.SM")
    }

    object Boolean {
        val CurrentThemeIsDark = ThemeTokenAccessor("Sem.Boolean.CurrentThemeIsDark")
        val CurrentThemeIsLight = ThemeTokenAccessor("Sem.Boolean.CurrentThemeIsLight")
    }

    object BorderRadius {
        val Group = ThemeTokenAccessor("Sem.BorderRadius.Group")
        val Image = ThemeTokenAccessor("Sem.BorderRadius.Image")
        val MD = ThemeTokenAccessor("Sem.BorderRadius.MD")
        val Max = ThemeTokenAccessor("Sem.BorderRadius.Max")
        val None = ThemeTokenAccessor("Sem.BorderRadius.None")

        object Action {
            val Button = ThemeTokenAccessor("Sem.BorderRadius.Action.Button")
        }

        object Form {
            val Control = ThemeTokenAccessor("Sem.BorderRadius.Form.Control")
            val Input = ThemeTokenAccessor("Sem.BorderRadius.Form.Input")
        }

        object Navigation {
            val NavigationItem = ThemeTokenAccessor("Sem.BorderRadius.Navigation.NavigationItem")
        }
    }

    object BorderWidth {
        val FocusRing = ThemeTokenAccessor("Sem.BorderWidth.FocusRing")
        val LG = ThemeTokenAccessor("Sem.BorderWidth.LG")
        val MD = ThemeTokenAccessor("Sem.BorderWidth.MD")
        val None = ThemeTokenAccessor("Sem.BorderWidth.None")
        val SM = ThemeTokenAccessor("Sem.BorderWidth.SM")
        val XL = ThemeTokenAccessor("Sem.BorderWidth.XL")

        object Action {
            val Hover = ThemeTokenAccessor("Sem.BorderWidth.Action.Hover")
            val Idle = ThemeTokenAccessor("Sem.BorderWidth.Action.Idle")
            val Pressed = ThemeTokenAccessor("Sem.BorderWidth.Action.Pressed")
        }

        object Forms {
            val Active = ThemeTokenAccessor("Sem.BorderWidth.Forms.Active")
            val Hover = ThemeTokenAccessor("Sem.BorderWidth.Forms.Hover")
            val Idle = ThemeTokenAccessor("Sem.BorderWidth.Forms.Idle")
            val Pressed = ThemeTokenAccessor("Sem.BorderWidth.Forms.Pressed")
        }

        object Group {
            val Hover = ThemeTokenAccessor("Sem.BorderWidth.Group.Hover")
            val Idle = ThemeTokenAccessor("Sem.BorderWidth.Group.Idle")
            val Pressed = ThemeTokenAccessor("Sem.BorderWidth.Group.Pressed")
        }

        object Navigation {
            val Underline = ThemeTokenAccessor("Sem.BorderWidth.Navigation.Underline")
        }
    }

    object Color {
        object Content {
            val Primary = ThemeTokenAccessor("Sem.Color.Content.Primary")
            val PrimaryInverted = ThemeTokenAccessor("Sem.Color.Content.PrimaryInverted")
            val PrimaryStatic = ThemeTokenAccessor("Sem.Color.Content.PrimaryStatic")
            val Quaternary = ThemeTokenAccessor("Sem.Color.Content.Quaternary")
            val QuaternaryInverted = ThemeTokenAccessor("Sem.Color.Content.QuaternaryInverted")
            val Secondary = ThemeTokenAccessor("Sem.Color.Content.Secondary")
            val SecondaryInverted = ThemeTokenAccessor("Sem.Color.Content.SecondaryInverted")
            val Tertiary = ThemeTokenAccessor("Sem.Color.Content.Tertiary")
            val TertiaryInverted = ThemeTokenAccessor("Sem.Color.Content.TertiaryInverted")
            val Transparent = ThemeTokenAccessor("Sem.Color.Content.Transparent")

            object OnSignal {
                val Advisory = ThemeTokenAccessor("Sem.Color.Content.OnSignal.Advisory")
                val Critical = ThemeTokenAccessor("Sem.Color.Content.OnSignal.Critical")
                val Informative = ThemeTokenAccessor("Sem.Color.Content.OnSignal.Informative")
                val Neutral = ThemeTokenAccessor("Sem.Color.Content.OnSignal.Neutral")
                val Positive = ThemeTokenAccessor("Sem.Color.Content.OnSignal.Positive")
                val Warning = ThemeTokenAccessor("Sem.Color.Content.OnSignal.Warning")
            }

            object Signal {
                val Advisory = ThemeTokenAccessor("Sem.Color.Content.Signal.Advisory")
                val Critical = ThemeTokenAccessor("Sem.Color.Content.Signal.Critical")
                val Informative = ThemeTokenAccessor("Sem.Color.Content.Signal.Informative")
                val Neutral = ThemeTokenAccessor("Sem.Color.Content.Signal.Neutral")
                val Positive = ThemeTokenAccessor("Sem.Color.Content.Signal.Positive")
                val Warning = ThemeTokenAccessor("Sem.Color.Content.Signal.Warning")
            }
        }

        object Fill {
            val Canvas = ThemeTokenAccessor("Sem.Color.Fill.Canvas")
            val Container = ThemeTokenAccessor("Sem.Color.Fill.Container")
            val Group = ThemeTokenAccessor("Sem.Color.Fill.Group")
            val Input = ThemeTokenAccessor("Sem.Color.Fill.Input")
            val Primary = ThemeTokenAccessor("Sem.Color.Fill.Primary")
            val Prominent = ThemeTokenAccessor("Sem.Color.Fill.Prominent")
            val Scrim = ThemeTokenAccessor("Sem.Color.Fill.Scrim")
            val Secondary = ThemeTokenAccessor("Sem.Color.Fill.Secondary")
            val Skeleton = ThemeTokenAccessor("Sem.Color.Fill.Skeleton")
            val Tertiary = ThemeTokenAccessor("Sem.Color.Fill.Tertiary")
            val Transparent = ThemeTokenAccessor("Sem.Color.Fill.Transparent")

            object Selected {
                val Strong = ThemeTokenAccessor("Sem.Color.Fill.Selected.Strong")
                val Subtle = ThemeTokenAccessor("Sem.Color.Fill.Selected.Subtle")
            }

            object Signal {
                val Advisory = ThemeTokenAccessor("Sem.Color.Fill.Signal.Advisory")
                val Critical = ThemeTokenAccessor("Sem.Color.Fill.Signal.Critical")
                val Informative = ThemeTokenAccessor("Sem.Color.Fill.Signal.Informative")
                val Neutral = ThemeTokenAccessor("Sem.Color.Fill.Signal.Neutral")
                val Positive = ThemeTokenAccessor("Sem.Color.Fill.Signal.Positive")
                val Warning = ThemeTokenAccessor("Sem.Color.Fill.Signal.Warning")
            }
        }

        object Graph {
            val Charging = ThemeTokenAccessor("Sem.Color.Graph.Charging")

            object Temperature {
                val Cold = ThemeTokenAccessor("Sem.Color.Graph.Temperature.Cold")
                val Hot = ThemeTokenAccessor("Sem.Color.Graph.Temperature.Hot")
            }
        }

        object ShadowColor {
            val Primary = ThemeTokenAccessor("Sem.Color.ShadowColor.Primary")
            val Secondary = ThemeTokenAccessor("Sem.Color.ShadowColor.Secondary")
        }

        object StateLayer {
            object Bold {
                val Hover = ThemeTokenAccessor("Sem.Color.StateLayer.Bold.Hover")
                val Pressed = ThemeTokenAccessor("Sem.Color.StateLayer.Bold.Pressed")
            }

            object Medium {
                val Hover = ThemeTokenAccessor("Sem.Color.StateLayer.Medium.Hover")
                val Pressed = ThemeTokenAccessor("Sem.Color.StateLayer.Medium.Pressed")
            }

            object Strong {
                val Hover = ThemeTokenAccessor("Sem.Color.StateLayer.Strong.Hover")
                val Pressed = ThemeTokenAccessor("Sem.Color.StateLayer.Strong.Pressed")
            }

            object Subtle {
                val Hover = ThemeTokenAccessor("Sem.Color.StateLayer.Subtle.Hover")
                val Pressed = ThemeTokenAccessor("Sem.Color.StateLayer.Subtle.Pressed")
            }
        }

        object Stroke {
            val Bold = ThemeTokenAccessor("Sem.Color.Stroke.Bold")
            val Medium = ThemeTokenAccessor("Sem.Color.Stroke.Medium")
            val MediumInverted = ThemeTokenAccessor("Sem.Color.Stroke.MediumInverted")
            val Prominent = ThemeTokenAccessor("Sem.Color.Stroke.Prominent")
            val Strong = ThemeTokenAccessor("Sem.Color.Stroke.Strong")
            val Subtle = ThemeTokenAccessor("Sem.Color.Stroke.Subtle")
            val Transparent = ThemeTokenAccessor("Sem.Color.Stroke.Transparent")

            object Signal {
                val Critical = ThemeTokenAccessor("Sem.Color.Stroke.Signal.Critical")
                val Focus = ThemeTokenAccessor("Sem.Color.Stroke.Signal.Focus")
                val Positive = ThemeTokenAccessor("Sem.Color.Stroke.Signal.Positive")
            }
        }
    }

    object FontFamily {
        val AudiFont = ThemeTokenAccessor("Sem.FontFamily.AudiFont")
        val Copy = ThemeTokenAccessor("Sem.FontFamily.Copy")
        val Display = ThemeTokenAccessor("Sem.FontFamily.Display")
        val Headline = ThemeTokenAccessor("Sem.FontFamily.Headline")
    }

    object FontSize {
        @Suppress("ktlint:standard:backing-property-naming")
        val _100 = ThemeTokenAccessor("Sem.FontSize.100")

        @Suppress("ktlint:standard:backing-property-naming")
        val _200 = ThemeTokenAccessor("Sem.FontSize.200")

        @Suppress("ktlint:standard:backing-property-naming")
        val _300 = ThemeTokenAccessor("Sem.FontSize.300")

        @Suppress("ktlint:standard:backing-property-naming")
        val _400 = ThemeTokenAccessor("Sem.FontSize.400")

        @Suppress("ktlint:standard:backing-property-naming")
        val _50 = ThemeTokenAccessor("Sem.FontSize.50")

        @Suppress("ktlint:standard:backing-property-naming")
        val _500 = ThemeTokenAccessor("Sem.FontSize.500")
    }

    object FontWeight {
        object Copy {
            val Bold = ThemeTokenAccessor("Sem.FontWeight.Copy.Bold")
            val Normal = ThemeTokenAccessor("Sem.FontWeight.Copy.Normal")
        }

        object Display {
            val Bold = ThemeTokenAccessor("Sem.FontWeight.Display.Bold")
            val Normal = ThemeTokenAccessor("Sem.FontWeight.Display.Normal")
        }

        object Headline {
            val Bold = ThemeTokenAccessor("Sem.FontWeight.Headline.Bold")
            val Normal = ThemeTokenAccessor("Sem.FontWeight.Headline.Normal")
        }
    }

    object Gradient {
        object Graph {
            val Temperature = ThemeTokenAccessor("Sem.Gradient.Graph.Temperature")
        }
    }

    object LetterSpacing {
        val None = ThemeTokenAccessor("Sem.LetterSpacing.None")
    }

    object LineHeight {
        @Suppress("ktlint:standard:backing-property-naming")
        object _100 {
            val Normal = ThemeTokenAccessor("Sem.LineHeight.100.Normal")
        }

        @Suppress("ktlint:standard:backing-property-naming")
        object _200 {
            val Normal = ThemeTokenAccessor("Sem.LineHeight.200.Normal")
            val Short = ThemeTokenAccessor("Sem.LineHeight.200.Short")
        }

        @Suppress("ktlint:standard:backing-property-naming")
        object _300 {
            val Normal = ThemeTokenAccessor("Sem.LineHeight.300.Normal")
            val Short = ThemeTokenAccessor("Sem.LineHeight.300.Short")
        }

        @Suppress("ktlint:standard:backing-property-naming")
        object _400 {
            val Normal = ThemeTokenAccessor("Sem.LineHeight.400.Normal")
            val Short = ThemeTokenAccessor("Sem.LineHeight.400.Short")
        }

        @Suppress("ktlint:standard:backing-property-naming")
        object _50 {
            val Normal = ThemeTokenAccessor("Sem.LineHeight.50.Normal")
        }

        @Suppress("ktlint:standard:backing-property-naming")
        object _500 {
            val Normal = ThemeTokenAccessor("Sem.LineHeight.500.Normal")
            val Short = ThemeTokenAccessor("Sem.LineHeight.500.Short")
        }
    }

    object Opacity {
        @Suppress("ktlint:standard:backing-property-naming")
        val _0_ = ThemeTokenAccessor("Sem.Opacity.0%")

        @Suppress("ktlint:standard:backing-property-naming")
        val _10_ = ThemeTokenAccessor("Sem.Opacity.10%")

        @Suppress("ktlint:standard:backing-property-naming")
        val _100_ = ThemeTokenAccessor("Sem.Opacity.100%")

        @Suppress("ktlint:standard:backing-property-naming")
        val _20_ = ThemeTokenAccessor("Sem.Opacity.20%")

        @Suppress("ktlint:standard:backing-property-naming")
        val _30_ = ThemeTokenAccessor("Sem.Opacity.30%")

        @Suppress("ktlint:standard:backing-property-naming")
        val _40_ = ThemeTokenAccessor("Sem.Opacity.40%")

        @Suppress("ktlint:standard:backing-property-naming")
        val _50_ = ThemeTokenAccessor("Sem.Opacity.50%")

        @Suppress("ktlint:standard:backing-property-naming")
        val _60_ = ThemeTokenAccessor("Sem.Opacity.60%")

        @Suppress("ktlint:standard:backing-property-naming")
        val _70_ = ThemeTokenAccessor("Sem.Opacity.70%")

        @Suppress("ktlint:standard:backing-property-naming")
        val _80_ = ThemeTokenAccessor("Sem.Opacity.80%")

        @Suppress("ktlint:standard:backing-property-naming")
        val _90_ = ThemeTokenAccessor("Sem.Opacity.90%")
        val Disabled = ThemeTokenAccessor("Sem.Opacity.Disabled")
    }

    object Shadow {
        object Elevation {
            val Level1 = ThemeTokenAccessor("Sem.Shadow.Elevation.Level1")
            val Level2 = ThemeTokenAccessor("Sem.Shadow.Elevation.Level2")
            val Level3 = ThemeTokenAccessor("Sem.Shadow.Elevation.Level3")
        }
    }

    object Size {
        val VisualReduction = ThemeTokenAccessor("Sem.Size.VisualReduction")

        object Fixed {
            @Suppress("ktlint:standard:backing-property-naming")
            val _0 = ThemeTokenAccessor("Sem.Size.Fixed.0")

            @Suppress("ktlint:standard:backing-property-naming")
            val _100 = ThemeTokenAccessor("Sem.Size.Fixed.100")

            @Suppress("ktlint:standard:backing-property-naming")
            val _1000 = ThemeTokenAccessor("Sem.Size.Fixed.1000")

            @Suppress("ktlint:standard:backing-property-naming")
            val _1200 = ThemeTokenAccessor("Sem.Size.Fixed.1200")

            @Suppress("ktlint:standard:backing-property-naming")
            val _125 = ThemeTokenAccessor("Sem.Size.Fixed.125")

            @Suppress("ktlint:standard:backing-property-naming")
            val _1400 = ThemeTokenAccessor("Sem.Size.Fixed.1400")

            @Suppress("ktlint:standard:backing-property-naming")
            val _150 = ThemeTokenAccessor("Sem.Size.Fixed.150")

            @Suppress("ktlint:standard:backing-property-naming")
            val _1600 = ThemeTokenAccessor("Sem.Size.Fixed.1600")

            @Suppress("ktlint:standard:backing-property-naming")
            val _1800 = ThemeTokenAccessor("Sem.Size.Fixed.1800")

            @Suppress("ktlint:standard:backing-property-naming")
            val _200 = ThemeTokenAccessor("Sem.Size.Fixed.200")

            @Suppress("ktlint:standard:backing-property-naming")
            val _2000 = ThemeTokenAccessor("Sem.Size.Fixed.2000")

            @Suppress("ktlint:standard:backing-property-naming")
            val _2100 = ThemeTokenAccessor("Sem.Size.Fixed.2100")

            @Suppress("ktlint:standard:backing-property-naming")
            val _2400 = ThemeTokenAccessor("Sem.Size.Fixed.2400")

            @Suppress("ktlint:standard:backing-property-naming")
            val _25 = ThemeTokenAccessor("Sem.Size.Fixed.25")

            @Suppress("ktlint:standard:backing-property-naming")
            val _250 = ThemeTokenAccessor("Sem.Size.Fixed.250")

            @Suppress("ktlint:standard:backing-property-naming")
            val _2600 = ThemeTokenAccessor("Sem.Size.Fixed.2600")

            @Suppress("ktlint:standard:backing-property-naming")
            val _2700 = ThemeTokenAccessor("Sem.Size.Fixed.2700")

            @Suppress("ktlint:standard:backing-property-naming")
            val _2800 = ThemeTokenAccessor("Sem.Size.Fixed.2800")

            @Suppress("ktlint:standard:backing-property-naming")
            val _300 = ThemeTokenAccessor("Sem.Size.Fixed.300")

            @Suppress("ktlint:standard:backing-property-naming")
            val _3000 = ThemeTokenAccessor("Sem.Size.Fixed.3000")

            @Suppress("ktlint:standard:backing-property-naming")
            val _3200 = ThemeTokenAccessor("Sem.Size.Fixed.3200")

            @Suppress("ktlint:standard:backing-property-naming")
            val _3400 = ThemeTokenAccessor("Sem.Size.Fixed.3400")

            @Suppress("ktlint:standard:backing-property-naming")
            val _3600 = ThemeTokenAccessor("Sem.Size.Fixed.3600")

            @Suppress("ktlint:standard:backing-property-naming")
            val _400 = ThemeTokenAccessor("Sem.Size.Fixed.400")

            @Suppress("ktlint:standard:backing-property-naming")
            val _450 = ThemeTokenAccessor("Sem.Size.Fixed.450")

            @Suppress("ktlint:standard:backing-property-naming")
            val _4800 = ThemeTokenAccessor("Sem.Size.Fixed.4800")

            @Suppress("ktlint:standard:backing-property-naming")
            val _50 = ThemeTokenAccessor("Sem.Size.Fixed.50")

            @Suppress("ktlint:standard:backing-property-naming")
            val _500 = ThemeTokenAccessor("Sem.Size.Fixed.500")

            @Suppress("ktlint:standard:backing-property-naming")
            val _600 = ThemeTokenAccessor("Sem.Size.Fixed.600")

            @Suppress("ktlint:standard:backing-property-naming")
            val _6000 = ThemeTokenAccessor("Sem.Size.Fixed.6000")

            @Suppress("ktlint:standard:backing-property-naming")
            val _700 = ThemeTokenAccessor("Sem.Size.Fixed.700")

            @Suppress("ktlint:standard:backing-property-naming")
            val _75 = ThemeTokenAccessor("Sem.Size.Fixed.75")

            @Suppress("ktlint:standard:backing-property-naming")
            val _800 = ThemeTokenAccessor("Sem.Size.Fixed.800")

            @Suppress("ktlint:standard:backing-property-naming")
            val _8000 = ThemeTokenAccessor("Sem.Size.Fixed.8000")

            @Suppress("ktlint:standard:backing-property-naming")
            val _900 = ThemeTokenAccessor("Sem.Size.Fixed.900")
            val Max = ThemeTokenAccessor("Sem.Size.Fixed.Max")
        }

        object TouchTarget {
            val MD = ThemeTokenAccessor("Sem.Size.TouchTarget.MD")
            val SM = ThemeTokenAccessor("Sem.Size.TouchTarget.SM")
        }

        object UnderlineThickness {
            @Suppress("ktlint:standard:backing-property-naming")
            val _100 = ThemeTokenAccessor("Sem.Size.UnderlineThickness.100")
        }
    }

    object Space {
        object Fixed {
            @Suppress("ktlint:standard:backing-property-naming")
            val _0 = ThemeTokenAccessor("Sem.Space.Fixed.0")

            @Suppress("ktlint:standard:backing-property-naming")
            val _100 = ThemeTokenAccessor("Sem.Space.Fixed.100")

            @Suppress("ktlint:standard:backing-property-naming")
            val _1000 = ThemeTokenAccessor("Sem.Space.Fixed.1000")

            @Suppress("ktlint:standard:backing-property-naming")
            val _1200 = ThemeTokenAccessor("Sem.Space.Fixed.1200")

            @Suppress("ktlint:standard:backing-property-naming")
            val _1400 = ThemeTokenAccessor("Sem.Space.Fixed.1400")

            @Suppress("ktlint:standard:backing-property-naming")
            val _150 = ThemeTokenAccessor("Sem.Space.Fixed.150")

            @Suppress("ktlint:standard:backing-property-naming")
            val _1600 = ThemeTokenAccessor("Sem.Space.Fixed.1600")

            @Suppress("ktlint:standard:backing-property-naming")
            val _200 = ThemeTokenAccessor("Sem.Space.Fixed.200")

            @Suppress("ktlint:standard:backing-property-naming")
            val _2000 = ThemeTokenAccessor("Sem.Space.Fixed.2000")

            @Suppress("ktlint:standard:backing-property-naming")
            val _2200 = ThemeTokenAccessor("Sem.Space.Fixed.2200")

            @Suppress("ktlint:standard:backing-property-naming")
            val _25 = ThemeTokenAccessor("Sem.Space.Fixed.25")

            @Suppress("ktlint:standard:backing-property-naming")
            val _250 = ThemeTokenAccessor("Sem.Space.Fixed.250")

            @Suppress("ktlint:standard:backing-property-naming")
            val _2600 = ThemeTokenAccessor("Sem.Space.Fixed.2600")

            @Suppress("ktlint:standard:backing-property-naming")
            val _300 = ThemeTokenAccessor("Sem.Space.Fixed.300")

            @Suppress("ktlint:standard:backing-property-naming")
            val _350 = ThemeTokenAccessor("Sem.Space.Fixed.350")

            @Suppress("ktlint:standard:backing-property-naming")
            val _400 = ThemeTokenAccessor("Sem.Space.Fixed.400")

            @Suppress("ktlint:standard:backing-property-naming")
            val _450 = ThemeTokenAccessor("Sem.Space.Fixed.450")

            @Suppress("ktlint:standard:backing-property-naming")
            val _50 = ThemeTokenAccessor("Sem.Space.Fixed.50")

            @Suppress("ktlint:standard:backing-property-naming")
            val _500 = ThemeTokenAccessor("Sem.Space.Fixed.500")

            @Suppress("ktlint:standard:backing-property-naming")
            val _600 = ThemeTokenAccessor("Sem.Space.Fixed.600")

            @Suppress("ktlint:standard:backing-property-naming")
            val _700 = ThemeTokenAccessor("Sem.Space.Fixed.700")

            @Suppress("ktlint:standard:backing-property-naming")
            val _800 = ThemeTokenAccessor("Sem.Space.Fixed.800")

            @Suppress("ktlint:standard:backing-property-naming")
            val _900 = ThemeTokenAccessor("Sem.Space.Fixed.900")
        }

        object UnderlineOffset {
            @Suppress("ktlint:standard:backing-property-naming")
            val _100 = ThemeTokenAccessor("Sem.Space.UnderlineOffset.100")

            @Suppress("ktlint:standard:backing-property-naming")
            val _200 = ThemeTokenAccessor("Sem.Space.UnderlineOffset.200")
        }
    }

    object Typography {
        object Caption {
            object Order1 {
                val Normal = ThemeTokenAccessor("Sem.Typography.Caption.Order1.Normal")
            }
        }

        object Copy {
            object Order1 {
                val Bold = ThemeTokenAccessor("Sem.Typography.Copy.Order1.Bold")
                val Normal = ThemeTokenAccessor("Sem.Typography.Copy.Order1.Normal")
            }

            object Order2 {
                val Bold = ThemeTokenAccessor("Sem.Typography.Copy.Order2.Bold")
                val Normal = ThemeTokenAccessor("Sem.Typography.Copy.Order2.Normal")
            }

            object Order3 {
                val Bold = ThemeTokenAccessor("Sem.Typography.Copy.Order3.Bold")
                val Normal = ThemeTokenAccessor("Sem.Typography.Copy.Order3.Normal")
            }

            object Order4 {
                val Bold = ThemeTokenAccessor("Sem.Typography.Copy.Order4.Bold")
                val Normal = ThemeTokenAccessor("Sem.Typography.Copy.Order4.Normal")
            }
        }

        object Display {
            object Order1 {
                val Normal = ThemeTokenAccessor("Sem.Typography.Display.Order1.Normal")
            }
        }

        object Headline {
            object Order1 {
                val Bold = ThemeTokenAccessor("Sem.Typography.Headline.Order1.Bold")
                val Normal = ThemeTokenAccessor("Sem.Typography.Headline.Order1.Normal")
            }

            object Order2 {
                val Bold = ThemeTokenAccessor("Sem.Typography.Headline.Order2.Bold")
                val Normal = ThemeTokenAccessor("Sem.Typography.Headline.Order2.Normal")
            }
        }

        object Label {
            object Order1 {
                val Bold = ThemeTokenAccessor("Sem.Typography.Label.Order1.Bold")
                val Normal = ThemeTokenAccessor("Sem.Typography.Label.Order1.Normal")
            }

            object Order2 {
                val Bold = ThemeTokenAccessor("Sem.Typography.Label.Order2.Bold")
                val Normal = ThemeTokenAccessor("Sem.Typography.Label.Order2.Normal")
            }

            object Order3 {
                val Bold = ThemeTokenAccessor("Sem.Typography.Label.Order3.Bold")
                val Normal = ThemeTokenAccessor("Sem.Typography.Label.Order3.Normal")
            }

            object Order4 {
                val Bold = ThemeTokenAccessor("Sem.Typography.Label.Order4.Bold")
                val Normal = ThemeTokenAccessor("Sem.Typography.Label.Order4.Normal")
            }
        }

        object Link {
            object Order1 {
                val Bold = ThemeTokenAccessor("Sem.Typography.Link.Order1.Bold")
                val Normal = ThemeTokenAccessor("Sem.Typography.Link.Order1.Normal")
            }

            object Order2 {
                val Bold = ThemeTokenAccessor("Sem.Typography.Link.Order2.Bold")
                val Normal = ThemeTokenAccessor("Sem.Typography.Link.Order2.Normal")
            }

            object Order3 {
                val Bold = ThemeTokenAccessor("Sem.Typography.Link.Order3.Bold")
                val Normal = ThemeTokenAccessor("Sem.Typography.Link.Order3.Normal")
            }

            object Order4 {
                val Bold = ThemeTokenAccessor("Sem.Typography.Link.Order4.Bold")
                val Normal = ThemeTokenAccessor("Sem.Typography.Link.Order4.Normal")
            }
        }
    }
}
